export const nigerianStates = [
  {
    name: "Federal Capital Territory (FCT)",
    cities: [
      "Abuja (City Centre)",
      "Garki",
      "Wuse",
      "Maitama",
      "Asokoro",
      "Jahi",
      "Gudu",
      "Utako",
      "Kubwa",
      "Gwarinpa",
      "Dutse",
      "Bwari",
      "Lugbe",
      "Karu",
      "Nyanya",
      "Jikwoyi",
      "Kuje",
      "Gwagwalada",
      "Kwali",
      "Abaji",
    ],
  },
  {
    name: "Lagos",
    cities: [
      "Lagos Island",
      "Ikeja",
      "Victoria Island (VI)",
      "Lekki",
      "Ajah",
      "Surulere",
      "Yaba",
      "Apapa",
      "Oshodi",
      "Agege",
      "Ikorodu",
      "Badagry",
      "Epe",
      "Alimosho",
      "Ifako-Ijaiye",
      "Mushin",
      "Amuwo-Odofin",
      "Kosofe",
      "Shomolu",
      "Ojo",
    ],
  },
  {
    name: "Kaduna",
    cities: [
      "Kaduna",
      "Zaria",
      "Kafanchan",
      "Sabon Gari",
      "Tudun Wada",
      "Malali",
      "Ungwan Rimi",
      "Barnawa",
      "Kakuri",
      "Kawo",
      "Rigasa",
      "Nasarawa",
      "Trikania",
      "Jaji",
      "Mando",
      "Kujama",
      "Jere",
      "Saminaka",
      "Birnin Gwari",
      "Giwa",
    ],
  },
  {
    name: "Kano",
    cities: [
      "Kano City",
      "Fagge",
      "Dala",
      "Gwale",
      "Kumbotso",
      "Nasarawa",
      "Tarauni",
      "Ungogo",
      "Dawakin Tofa",
      "Gwarzo",
      "Bichi",
      "Rano",
      "Wudil",
      "Gaya",
      "Kabo",
      "Kura",
      "Madobi",
      "Tofa",
      "Karaye",
      "Rimin Gado",
    ],
  },
];
